### ISSUE TITLE
dry run and output the result in YAML format

### ISSUE THREAD

**Issue by suzuki-shunsuke** [suzuki-shunsuke/tfmigrator#21]
```yaml
migrated_resources:
- source_resource_path: aws_iam_role.foo
  dest_resource_path: aws_iam_role.foo
  tf_path: foo.tf
  state_out: terraform.tfstate
excluded_resources:
- aws_iam_role.bar
no_match_resources:
- aws_iam_role.bar
```

```
$ tfmigrator run -dry-run -o yaml
```
